### ISSUE TITLE
 Modpacks

### ISSUE THREAD

**Issue by TheMulhima** [TheMulhima/Scarab#4]
# TODO
- [x] Create UI for managing packs
- [x] Add code for adding/removing packs
- [x] Add UI for editing packs
- [ ] Add code for adding additional assets
- [x] Add code for sharing pack via sharing code
- [x] Add code for manual sharing

**Comment by TheMulhima** [comment]
# Plan for implementation

## Creating/Editing the pack
When create pack is pressed ask for pack name and description. Then copy the Mods folder and paste it in the Managed folder and rename it to PackName. Then get the mods in PackName and add it to `packMods.json`. If the user wants to edit the pack, it will edit the list in `packMods.json`

## Loading the pack
To load the pack, Scarab will replace the current mods folder with the Pack folder and then do the required steps to make it match with `packMods.json`. To make this operation faster in the future, if the mods were edited, recopy them into the pack folder

## Sharing the pack
To share the pack, there will be a button in the pack list that when pressed will use the `packMods.json` to generate a JSON compatible with the [hpackage-schema](https://github.com/hpackage/hpackage-schema). By default, no additional assets will be added so it will prompt to add them if required. Any additional assets will be stored as text if < 1MB, or using [catbox](https://catbox.moe/) if < 200MB. Then the JSON will be uploaded to pastebin and 8 digit identifier of the [pastebin](https://pastebin.com/) will be the "sharing code" This code can be used to import packs

### Manual Sharing
Since [catbox](https://catbox.moe/) and [pastebin](https://pastebin.com/) don't have usability garuntees (because they are free) there will be an option for manual sharing which will just just zip the pack folder and ask where to save it. Then user can manually share it and the other user can press import pack and install it

## UI
Initial UI design idea: <https://www.figma.com/community/file/1251576832566083349>    

Basic UI Requirements are:
  - Add a new tab for mod packs. The main page will have the list of packs and buttons for create pack and import pack at the bottom
  - Add a window for create pack that has boxes for name and description
  - Add a window for edit pack which allows you to add/remove mods and add additional assets

**Comment by Acu1000** [comment]
I suppose the mods that are in modlinks and aren't prevented from auto-updaing could be stored as simply a list (probably .json) of names rather than copying the whole thing

**Comment by TheMulhima** [comment]
Yea that was thought of initially but what then came up is it shouldn't be a task to change a modpack. Copying the folder locally regardless if it wants to be fixed version or not would greatly improve pack changing speed
